### ISSUE TITLE
[BUG] CMI Addon

### ISSUE THREAD

**Issue by MatinHQ** [timderspieler/DeluxeCombat-API#1]
I am using CMI 9.5.12 and when I install this addon none of addon feature works and it disables the PVP entirely

**Comment by timderspieler** [comment]
The addon has been updated :) 

Please restart your server so you can see the update!

**Comment by MatinHQ** [comment]
It solves previous issue whoever it still doesn't behave as it should be I enabled disable god and vanish in combat but its only preventing PVP while one of those are enabled
